import { formatCalendarDate } from "@/lib/dates";
import type { LedgerRow } from "@/modules/ledger";

const HEADERS = [
  "Project code",
  "Project name",
  "Client type",
  "Client name",
  "Project completion date",
  "Recipient",
  "Role on project",
  "Currency",
  "Original amount owed",
  "Adjustments",
  "Amount owed after adjustments",
  "Amount paid",
  "Remaining balance",
  "Payout status",
  "Payments (date amount method reference)",
  "Approved by",
  "Approved on",
];

const major = (minor: number) => `${minor < 0 ? "-" : ""}${Math.floor(Math.abs(minor) / 100)}.${String(Math.abs(minor) % 100).padStart(2, "0")}`;

/** Quotes a CSV field and neutralises spreadsheet formulas in text (CSV injection). */
export function csvField(value: string): string {
  const safe = /^[=+\-@\t\r]/.test(value) ? `'${value}` : value;
  return `"${safe.replace(/"/g, '""')}"`;
}

/** Amounts are generated by the app (never user text), so a leading minus must stay a number. */
const amountField = (minor: number) => `"${major(minor)}"`;

type Cell = string | { amount: number };

export function toCsv(headers: string[], rows: Cell[][]): string {
  const lines = rows.map((cells) => cells.map((v) => (typeof v === "object" ? amountField(v.amount) : csvField(v))).join(","));
  // BOM so Excel opens UTF-8 correctly.
  return `\uFEFF${headers.map(csvField).join(",")}\r\n${lines.join("\r\n")}${lines.length ? "\r\n" : ""}`;
}

/** Ledger export for bookkeeping review (design doc section 10). Amounts in major units, 2 decimals. */
export function ledgerToCsv(rows: LedgerRow[]): string {
  return toCsv(
    HEADERS,
    rows.map((r) => [
      r.projectCode,
      r.projectName,
      r.clientType === "INTERNAL" ? "Internal" : "External",
      r.clientName ?? "",
      r.completedAt ? formatCalendarDate(r.completedAt.toISOString().slice(0, 10)) : "",
      r.memberName,
      r.roleOnProject,
      r.currency,
      { amount: r.originalMinor },
      { amount: r.adjustmentsMinor },
      { amount: r.effectiveOwedMinor },
      { amount: r.paidMinor },
      { amount: r.remainingMinor },
      r.status,
      r.payments
        .map((p) => `${p.paidAt.toISOString().slice(0, 10)} ${major(p.amountMinor)} ${p.method}${p.reference ? ` ${p.reference}` : ""}`)
        .join("; "),
      r.approvedByName,
      r.approvedAt.toISOString().slice(0, 10),
    ]),
  );
}

export type PeriodMovement = {
  date: Date;
  kind: "PAYMENT" | "INCREASE" | "DECREASE" | "WRITE_OFF" | "VOID";
  projectCode: string;
  memberName: string;
  currency: string;
  /** Payments and increases positive; decreases and write-offs negative; voids zero. */
  amountMinor: number;
  method: string | null;
  reference: string | null;
  note: string | null;
};

/** Month-close export (roadmap 2.9): every payment and adjustment in the month, oldest first. */
export function periodToCsv(movements: PeriodMovement[]): string {
  return toCsv(
    ["Date", "Type", "Project code", "Recipient", "Currency", "Amount", "Method", "Reference", "Reason or notes"],
    [...movements]
      .sort((a, b) => a.date.getTime() - b.date.getTime())
      .map((m) => [
        m.date.toISOString().slice(0, 10),
        m.kind,
        m.projectCode,
        m.memberName,
        m.currency,
        { amount: m.amountMinor },
        m.method ?? "",
        m.reference ?? "",
        m.note ?? "",
      ]),
  );
}

export type ProfitabilityCsvRow = {
  code: string;
  name: string;
  status: string;
  category: string;
  clientName: string | null;
  clientType: string;
  revenueMinor: number;
  plannedPayoutMinor: number;
  committedPayoutMinor: number;
  paidPayoutMinor: number;
  costBudgetMinor: number;
  actualCostMinor: number;
  estimatedProfitMinor: number;
  actualProfitMinor: number;
  actualMarginPct: number | null;
};

/** Stage 3 profitability export: one row per project, amounts in GHS. */
export function profitabilityToCsv(rows: ProfitabilityCsvRow[]): string {
  return toCsv(
    [
      "Project code",
      "Project name",
      "Status",
      "Type",
      "Client",
      "Revenue",
      "Planned payouts",
      "Committed payouts",
      "Paid payouts",
      "Cost budget",
      "Recorded costs",
      "Estimated profit",
      "Actual profit",
      "Actual margin %",
    ],
    rows.map((r) => [
      r.code,
      r.name,
      r.status,
      r.category,
      r.clientType === "INTERNAL" ? "Internal" : (r.clientName ?? ""),
      { amount: r.revenueMinor },
      { amount: r.plannedPayoutMinor },
      { amount: r.committedPayoutMinor },
      { amount: r.paidPayoutMinor },
      { amount: r.costBudgetMinor },
      { amount: r.actualCostMinor },
      { amount: r.estimatedProfitMinor },
      { amount: r.actualProfitMinor },
      r.actualMarginPct === null ? "" : String(r.actualMarginPct),
    ]),
  );
}
